CREATE TABLE "cliente" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100),
  "email" varchar(150) UNIQUE,
  "cnpj" varchar(14) UNIQUE,
  "telefone" varchar(20)
);

CREATE TABLE "conselho" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar(100),
  "descricao" text,
  "tipo" varchar(20)
);

CREATE TABLE "venda" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" int,
  "data_venda" timestamp,
  "valor_total" decimal(10,2)
);

CREATE TABLE "venda_conselho" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_venda" int,
  "id_conselho" int
);

CREATE TABLE "agendamento" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" int,
  "id_conselho" int,
  "data_hora_agendada" timestamp
);

ALTER TABLE "venda" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id");

ALTER TABLE "venda_conselho" ADD FOREIGN KEY ("id_venda") REFERENCES "venda" ("id");

ALTER TABLE "venda_conselho" ADD FOREIGN KEY ("id_conselho") REFERENCES "conselho" ("id");

ALTER TABLE "agendamento" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id");

ALTER TABLE "agendamento" ADD FOREIGN KEY ("id_conselho") REFERENCES "conselho" ("id");
